language : c

services:
  - docker

before_install:
  - echo "=== Before Install ==="

script:
  - make

rvm:
  - 1.0.3
  - 2.0.0
  - 2.1.0

env:
  - DB=mongdb SUITE=all
  - DB=mongdb SUITE=compact

after_install:
  - echo "=== After Install ==="
  - docker version
  - docker-compose version
