language : c

services:
  - docker

before_install:
  - echo "=== Before Install ==="

script:
  - make
  - gol

after_install:
  - echo "=== After Install ==="
  - docker version
  - docker-compose version
